### ISSUE TITLE
Программа создает слишком много потоков

### ISSUE THREAD

**Issue by PerchunPak** [JustNanix/Wave-Multibot#3]
Из за этого не возможно её поставить на pterodactyl панель.

**Comment by VzlomPidarasa** [comment]
ЕТО ВИРУС

он запускает с твоего пк ботов и может удалить виндовс

**Comment by PerchunPak** [comment]
Сначала читай код, а затем уже делай какие либо предположения.
После _достаточно_ тщательного исследования, я понял что это простой open-source бот создающий около 100 потоков при запуске (а может и больше).

**Comment by VzlomPidarasa** [comment]
Чел нахуй ето вирус я тебе говорю

**Comment by VzlomPidarasa** [comment]
соболезную твоему пк

**Comment by cofob** [comment]
БЛЯТТ ЙА ТОЖИ СКОЧАЛ И ТЕПЕР У МИНЯ АРЧ ЛИНУСК ВМЕСТА ШИНДАУС УСТАНАВИЛСЙА. ДЕФФАВЧКИ, ПАМАГИТЕ!!
